package docker

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type projectType struct {
	Name        string
	TriggerFile string
	Dockerfile  string
}

var projectTypes = []projectType{
	{
		Name:        "Node.js",
		TriggerFile: "package.json",
		Dockerfile: `FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
`,
	},
	{
		Name:        "Python",
		TriggerFile: "requirements.txt",
		Dockerfile: `FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "app.py"]
`,
	},
	{
		Name:        "Go",
		TriggerFile: "go.mod",
		Dockerfile: `FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o server .

FROM alpine:3.19
WORKDIR /app
COPY --from=build /app/server .
EXPOSE 8080
CMD ["./server"]
`,
	},
	{
		Name:        "PHP",
		TriggerFile: "composer.json",
		Dockerfile: `FROM composer:2 AS deps
WORKDIR /app
COPY composer.json composer.lock* ./
RUN composer install --no-dev --no-scripts --ignore-platform-reqs

FROM php:8.3-apache
RUN docker-php-ext-install pdo pdo_mysql
COPY . /var/www/html/
COPY --from=deps /app/vendor /var/www/html/vendor
EXPOSE 80
`,
	},
	{
		Name:        "Rust",
		TriggerFile: "Cargo.toml",
		Dockerfile: `FROM rust:1.77 AS build
WORKDIR /app
COPY . .
RUN cargo build --release
RUN cp target/release/$(cargo metadata --format-version=1 --no-deps | grep -o '"name":"[^"]*"' | head -1 | cut -d'"' -f4) /app/server || cp target/release/app /app/server

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=build /app/server .
EXPOSE 8080
CMD ["./server"]
`,
	},
	{
		Name:        "Static HTML",
		TriggerFile: "index.html",
		Dockerfile: `FROM nginx:alpine
COPY . /usr/share/nginx/html/
EXPOSE 80
`,
	},
}

func autoGenerateDockerFiles(dir, name string) error {
	composePath := filepath.Join(dir, "docker-compose.yml")
	dockerfilePath := filepath.Join(dir, "Dockerfile")
	if _, ok := findComposeFilePath(dir); ok {
		return nil
	}
	for _, pt := range projectTypes {
		if _, err := os.Stat(filepath.Join(dir, pt.TriggerFile)); err == nil {
			if _, err := os.Stat(dockerfilePath); os.IsNotExist(err) {
				if err := writeFileAtomic(dockerfilePath, []byte(pt.Dockerfile), 0644); err != nil {
					return err
				}
			}
			return writeBasicComposeFile(composePath, name)
		}
	}
	return fmt.Errorf("no compose file found and could not auto-detect project type (expected one of: %s)", triggerFileList())
}

func triggerFileList() string {
	names := make([]string, len(projectTypes))
	for i, pt := range projectTypes {
		names[i] = pt.TriggerFile
	}
	return strings.Join(names, ", ")
}

func writeBasicComposeFile(path, name string) error {
	serviceName := strings.ToLower(strings.ReplaceAll(name, " ", "-"))
	content := fmt.Sprintf(`services:
  %s:
    build: .
    restart: unless-stopped
`, serviceName)
	return writeFileAtomic(path, []byte(content), 0644)
}

func detectsAsKnownType(dir string) bool {
	for _, pt := range projectTypes {
		if _, err := os.Stat(filepath.Join(dir, pt.TriggerFile)); err == nil {
			return true
		}
	}
	return false
}

func cleanupOrphanedDockerProjects(cfg AutoStartConfig, base string) {
	dirty := false
	for name := range cfg.DockerProjects {
		dir := filepath.Join(base, name)
		if _, err := os.Stat(dir); os.IsNotExist(err) {
			if _, ok := findComposeFilePath(dir); ok {
				_ = runCompose(dir, "down", "--volumes", "--remove-orphans")
			}
			delete(cfg.DockerProjects, name)
			dirty = true
		}
	}
	if dirty {
		_ = SaveAutoStartConfig(cfg)
	}
}

func cleanupOrphanedHtmlSites(cfg AutoStartConfig, base string) {
	dirty := false
	for name := range cfg.HtmlSites {
		dir := filepath.Join(base, name)
		if _, err := os.Stat(dir); os.IsNotExist(err) {
			_, _ = runDockerCmd(defaultTimeout, "", "rm", "-f", "html-"+name)
			delete(cfg.HtmlSites, name)
			dirty = true
		}
	}
	if dirty {
		_ = SaveAutoStartConfig(cfg)
	}
}